/**
 * Default Achievements for CleverCourse
 *
 * This file contains all the predefined achievements that will be
 * seeded into the database when the app starts.
 */

import type { NewAchievement } from "./types";

export const DEFAULT_ACHIEVEMENTS: NewAchievement[] = [
  // ============================================================================
  // LEARNING ACHIEVEMENTS
  // ============================================================================
  {
    id: "first_section",
    name: "First Steps",
    description: "Complete your first course section",
    iconName: "BookOpen",
    category: "learning",
    rarity: "common",
    xpReward: 50,
    sparksReward: 10,
    conditionType: "sections_completed",
    conditionValue: 1,
    isHidden: false,
  },
  {
    id: "section_5",
    name: "Getting Started",
    description: "Complete 5 course sections",
    iconName: "BookMarked",
    category: "learning",
    rarity: "common",
    xpReward: 100,
    sparksReward: 20,
    conditionType: "sections_completed",
    conditionValue: 5,
    isHidden: false,
  },
  {
    id: "section_25",
    name: "Dedicated Learner",
    description: "Complete 25 course sections",
    iconName: "GraduationCap",
    category: "learning",
    rarity: "rare",
    xpReward: 250,
    sparksReward: 50,
    conditionType: "sections_completed",
    conditionValue: 25,
    isHidden: false,
  },
  {
    id: "section_100",
    name: "Knowledge Seeker",
    description: "Complete 100 course sections",
    iconName: "Brain",
    category: "learning",
    rarity: "epic",
    xpReward: 500,
    sparksReward: 100,
    conditionType: "sections_completed",
    conditionValue: 100,
    isHidden: false,
  },
  {
    id: "first_course",
    name: "Course Champion",
    description: "Complete your first full course",
    iconName: "Trophy",
    category: "learning",
    rarity: "rare",
    xpReward: 200,
    sparksReward: 50,
    conditionType: "courses_completed",
    conditionValue: 1,
    isHidden: false,
  },
  {
    id: "courses_5",
    name: "Multi-Disciplinary",
    description: "Complete 5 courses",
    iconName: "Medal",
    category: "learning",
    rarity: "epic",
    xpReward: 500,
    sparksReward: 100,
    conditionType: "courses_completed",
    conditionValue: 5,
    isHidden: false,
  },

  // ============================================================================
  // STREAK ACHIEVEMENTS
  // ============================================================================
  {
    id: "streak_3",
    name: "Warm Up",
    description: "Maintain a 3-day learning streak",
    iconName: "Flame",
    category: "streak",
    rarity: "common",
    xpReward: 75,
    sparksReward: 15,
    conditionType: "streak_days",
    conditionValue: 3,
    isHidden: false,
  },
  {
    id: "streak_7",
    name: "Weekly Warrior",
    description: "Maintain a 7-day learning streak",
    iconName: "Flame",
    category: "streak",
    rarity: "rare",
    xpReward: 150,
    sparksReward: 30,
    conditionType: "streak_days",
    conditionValue: 7,
    isHidden: false,
  },
  {
    id: "streak_14",
    name: "Fortnight Focus",
    description: "Maintain a 14-day learning streak",
    iconName: "Flame",
    category: "streak",
    rarity: "rare",
    xpReward: 300,
    sparksReward: 60,
    conditionType: "streak_days",
    conditionValue: 14,
    isHidden: false,
  },
  {
    id: "streak_30",
    name: "Monthly Master",
    description: "Maintain a 30-day learning streak",
    iconName: "Flame",
    category: "streak",
    rarity: "epic",
    xpReward: 500,
    sparksReward: 100,
    conditionType: "streak_days",
    conditionValue: 30,
    isHidden: false,
  },
  {
    id: "streak_100",
    name: "Unstoppable",
    description: "Maintain a 100-day learning streak",
    iconName: "Zap",
    category: "streak",
    rarity: "legendary",
    xpReward: 1000,
    sparksReward: 250,
    conditionType: "streak_days",
    conditionValue: 100,
    isHidden: true,
  },

  // ============================================================================
  // MASTERY ACHIEVEMENTS
  // ============================================================================
  {
    id: "quiz_first",
    name: "Quiz Taker",
    description: "Complete your first quiz",
    iconName: "CheckCircle",
    category: "mastery",
    rarity: "common",
    xpReward: 25,
    sparksReward: 5,
    conditionType: "quizzes_passed",
    conditionValue: 1,
    isHidden: false,
  },
  {
    id: "quiz_10",
    name: "Quiz Enthusiast",
    description: "Complete 10 quizzes",
    iconName: "ListChecks",
    category: "mastery",
    rarity: "common",
    xpReward: 100,
    sparksReward: 20,
    conditionType: "quizzes_passed",
    conditionValue: 10,
    isHidden: false,
  },
  {
    id: "quiz_50",
    name: "Quiz Master",
    description: "Complete 50 quizzes",
    iconName: "Award",
    category: "mastery",
    rarity: "rare",
    xpReward: 250,
    sparksReward: 50,
    conditionType: "quizzes_passed",
    conditionValue: 50,
    isHidden: false,
  },
  {
    id: "perfect_1",
    name: "Perfectionist",
    description: "Score 100% on a quiz",
    iconName: "Star",
    category: "mastery",
    rarity: "rare",
    xpReward: 100,
    sparksReward: 25,
    conditionType: "perfect_quizzes",
    conditionValue: 1,
    isHidden: false,
  },
  {
    id: "perfect_10",
    name: "Flawless",
    description: "Score 100% on 10 quizzes",
    iconName: "Stars",
    category: "mastery",
    rarity: "epic",
    xpReward: 300,
    sparksReward: 75,
    conditionType: "perfect_quizzes",
    conditionValue: 10,
    isHidden: false,
  },
  {
    id: "flashcards_50",
    name: "Card Collector",
    description: "Review 50 flashcards",
    iconName: "Layers",
    category: "mastery",
    rarity: "common",
    xpReward: 75,
    sparksReward: 15,
    conditionType: "flashcards_reviewed",
    conditionValue: 50,
    isHidden: false,
  },
  {
    id: "flashcards_500",
    name: "Memory Master",
    description: "Review 500 flashcards",
    iconName: "Sparkles",
    category: "mastery",
    rarity: "epic",
    xpReward: 400,
    sparksReward: 100,
    conditionType: "flashcards_reviewed",
    conditionValue: 500,
    isHidden: false,
  },

  // ============================================================================
  // LEVEL ACHIEVEMENTS
  // ============================================================================
  {
    id: "level_5",
    name: "Rising Star",
    description: "Reach Level 5",
    iconName: "TrendingUp",
    category: "special",
    rarity: "common",
    xpReward: 50,
    sparksReward: 25,
    conditionType: "level_reached",
    conditionValue: 5,
    isHidden: false,
  },
  {
    id: "level_10",
    name: "Established",
    description: "Reach Level 10",
    iconName: "Target",
    category: "special",
    rarity: "rare",
    xpReward: 100,
    sparksReward: 50,
    conditionType: "level_reached",
    conditionValue: 10,
    isHidden: false,
  },
  {
    id: "level_25",
    name: "Veteran",
    description: "Reach Level 25",
    iconName: "Crown",
    category: "special",
    rarity: "epic",
    xpReward: 250,
    sparksReward: 100,
    conditionType: "level_reached",
    conditionValue: 25,
    isHidden: false,
  },
  {
    id: "level_50",
    name: "Legend",
    description: "Reach Level 50",
    iconName: "Gem",
    category: "special",
    rarity: "legendary",
    xpReward: 500,
    sparksReward: 250,
    conditionType: "level_reached",
    conditionValue: 50,
    isHidden: true,
  },

  // ============================================================================
  // XP ACHIEVEMENTS
  // ============================================================================
  {
    id: "xp_1000",
    name: "Thousand Club",
    description: "Earn 1,000 XP",
    iconName: "Zap",
    category: "special",
    rarity: "common",
    xpReward: 50,
    sparksReward: 15,
    conditionType: "xp_earned",
    conditionValue: 1000,
    isHidden: false,
  },
  {
    id: "xp_10000",
    name: "XP Hunter",
    description: "Earn 10,000 XP",
    iconName: "Bolt",
    category: "special",
    rarity: "rare",
    xpReward: 200,
    sparksReward: 50,
    conditionType: "xp_earned",
    conditionValue: 10000,
    isHidden: false,
  },
  {
    id: "xp_100000",
    name: "XP Legend",
    description: "Earn 100,000 XP",
    iconName: "Infinity",
    category: "special",
    rarity: "legendary",
    xpReward: 1000,
    sparksReward: 500,
    conditionType: "xp_earned",
    conditionValue: 100000,
    isHidden: true,
  },
];
